services:
  pyxel-web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_DIR:        src
        STARTUP_SCRIPT: main.py
        APP_NAME:       game
        OUTPUT_DIR:     web

    ports:
      - "8000:80"

    container_name: pyxel-web
    restart: unless-stopped
